# Generated by Django 5.1.3 on 2024-11-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(help_text='Code de la devise (ex. : USD, EUR)', max_length=3, unique=True)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Taux de conversion par rapport à la devise par défaut', max_digits=10)),
            ],
        ),
    ]
